name: Data check
on:
  push:
    paths:
      - '**.csv'
    branches:
      - main
  pull_request:
    paths:
      - '**.csv'
jobs:
  check-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./tools/preflight-check.py ./umu-database.csv

